# Generated by Django 3.1.5 on 2021-07-12 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210712_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_pubdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
